[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-embed="6.2.0"
itertools = "0.10.1"
regex = "1.5.5"
rand = "0.8.1"
